### ISSUE TITLE
Smart Plug can't change State

### ISSUE THREAD

**Issue by hehljo** [ioBroker/ioBroker.mihome#1]
The Plug doesn't work. I played with the State of the Plug, but i can't get it work. All other Products works fine except the Smart Plug.
Any idea?

**Comment by GermanBluefox** [comment]
What can you see in debug log?

**Comment by wowik2018** [comment]
mihome.0 | 2019-06-12 19:54:38.532 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"ORv8P2kPg1BKCI7i","data":{"ip":"192.168.178.27"}}
-- | -- | -- | --
mihome.0 | 2019-06-12 19:54:28.496 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"XjaXZ79o78R5I8IT","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:54:18.564 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"NbE9Yipyp64xeRaH","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:54:12.934 | debug | RAW: {"cmd":"report","model":"motion","sid":"158d00022a8b06","short_id":28934,"data":{"no_motion":"120"}}
mihome.0 | 2019-06-12 19:54:12.933 | debug | data: 158d00022a8b06(motion): {"no_motion":120,"state":false}
mihome.0 | 2019-06-12 19:54:08.529 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"SThT4GVoBgUwIsHE","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:58.595 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"Zue5PFpbV56ou8vn","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:48.661 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"d1kFQxKM19YbOUsS","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:38.626 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"RWTzTZAz64DS3tsq","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:33.209 | debug | RAW: {"cmd":"heartbeat","model":"weather.v1","sid":"158d0002320f2c","short_id":38850,"data":{"voltage":3005,"temperature":"2449","humidity":"5003","pressure":"97652"}}
mihome.0 | 2019-06-12 19:53:33.209 | debug | data: 158d0002320f2c(weather.v1): {"voltage":3.005,"percent":64.2,"temperature":24.49,"humidity":50.03,"pressure":976.52}
mihome.0 | 2019-06-12 19:53:33.209 | debug | RAW: {"cmd":"report","model":"weather.v1","sid":"158d0002320f2c","short_id":38850,"data":{"pressure":"97652"}}
mihome.0 | 2019-06-12 19:53:33.209 | debug | data: 158d0002320f2c(weather.v1): {"pressure":976.52}
mihome.0 | 2019-06-12 19:53:33.209 | debug | RAW: {"cmd":"report","model":"weather.v1","sid":"158d0002320f2c","short_id":38850,"data":{"humidity":"5003"}}
mihome.0 | 2019-06-12 19:53:33.209 | debug | data: 158d0002320f2c(weather.v1): {"humidity":50.03}
mihome.0 | 2019-06-12 19:53:33.209 | debug | RAW: {"cmd":"report","model":"weather.v1","sid":"158d0002320f2c","short_id":38850,"data":{"temperature":"2449"}}
mihome.0 | 2019-06-12 19:53:33.208 | debug | data: 158d0002320f2c(weather.v1): {"temperature":24.49}
mihome.0 | 2019-06-12 19:53:28.692 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"btFFEP1T8ZF3RtHz","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:18.658 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"S0zgBmagEh7mm8pU","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:08.724 | debug | RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"OIraYlwt1kTu4Stc","data":{"ip":"192.168.178.27"}}
mihome.0 | 2019-06-12 19:53:08.526 | debug | RAW: {"cmd":"report","model":"magnet","sid":"158d00012a1876","short_id":22146,"data":{"status":"close"}}
mihome.0 | 2019-06-12 19:53:08.524 | debug | data: 158d00012a1876(magnet): {"state":false}
mihome.0 | 2019-06-12 19:53:04.165 | debug | RAW: {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d0002b6edf7","short_id":30717,"data":{"voltage":3025,"lux":"43"}}
mihome.0 | 2019-06-12 19:53:04.164 | debug | data: 158d0002b6edf7(sensor_motion.aq2): {"voltage":3.025,"percent":67.9,"lux":43}
mihome.0 | 2019-06-12 19:53:04.164 | debug | NEW device: 158d0002b6edf7(sensor_motion.aq2)
mihome.0 | 2019-06-12 19:53:04.164 | debug | RAW: {"cmd":"read_ack","model":"sensor_magnet.aq2","sid":"158d0002536e80","short_id":32757,"data":{"voltage":3035,"status":"open"}}
mihome.0 | 2019-06-12 19:53:04.164 | debug | data: 158d0002536e80(magnet): {"voltage":3.035,"percent":69.7,"state":true}
mihome.0 | 2019-06-12 19:53:04.164 | debug | NEW device: 158d0002536e80(sensor_magnet.aq2)
mihome.0 | 2019-06-12 19:53:04.164 | debug | RAW: {"cmd":"read_ack","model":"remote.b286acn01","sid":"158d0002829c5c","short_id":37,"data":{"voltage":3025}}
mihome.0 | 2019-06-12 19:53:04.164 | debug | data: 158d0002829c5c(remote.b286acn01): {"voltage":3.025,"percent":67.9}
mihome.0 | 2019-06-12 19:53:04.164 | debug | NEW device: 158d0002829c5c(remote.b286acn01)
mihome.0 | 2019-06-12 19:53:04.163 | debug | RAW: {"cmd":"read_ack","model":"sensor_magnet.aq2","sid":"158d00025296f4","short_id":50385,"data":{"voltage":3035,"status":"close"}}
mihome.0 | 2019-06-12 19:53:04.163 | debug | data: 158d00025296f4(magnet): {"voltage":3.035,"percent":69.7,"state":false}
mihome.0 | 2019-06-12 19:53:04.163 | debug | NEW device: 158d00025296f4(sensor_magnet.aq2)
mihome.0 | 2019-06-12 19:53:04.163 | debug | RAW: {"cmd":"read_ack","model":"weather.v1","sid":"158d0002320f2c","short_id":38850,"data":{"voltage":3005,"temperature":"2446","humidity":"5041","pressure":"97640"}}
mihome.0 | 2019-06-12 19:53:04.163 | debug | data: 158d0002320f2c(weather.v1): {"voltage":3.005,"percent":64.2,"temperature":24.46,"humidity":50.41,"pressure":976.4}
mihome.0 | 2019-06-12 19:53:04.163 | debug | NEW device: 158d0002320f2c(weather.v1)
mihome.0 | 2019-06-12 19:53:04.163 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d00026bb318","short_id":12240,"data":{"voltage":3052}}
mihome.0 | 2019-06-12 19:53:04.163 | debug | data: 158d00026bb318(switch): {"voltage":3.052,"percent":72.8}
mihome.0 | 2019-06-12 19:53:04.162 | debug | NEW device: 158d00026bb318(switch)
mihome.0 | 2019-06-12 19:53:04.162 | debug | RAW: {"cmd":"read_ack","model":"sensor_cube.aqgl01","sid":"158d000269e235","short_id":1873,"data":{"voltage":3005}}
mihome.0 | 2019-06-12 19:53:04.162 | debug | data: 158d000269e235(cube): {"voltage":3.005,"percent":64.2}
mihome.0 | 2019-06-12 19:53:04.162 | debug | NEW device: 158d000269e235(sensor_cube.aqgl01)
mihome.0 | 2019-06-12 19:53:04.162 | debug | RAW: {"cmd":"read_ack","model":"smoke","sid":"158d0001e827f6","short_id":29329,"data":{"voltage":3095,"alarm":false,"description":"Release alarm"}}
mihome.0 | 2019-06-12 19:53:04.162 | debug | data: 158d0001e827f6(smoke): {"voltage":3.095,"percent":80.7,"state":false,"description":"Release alarm"}
mihome.0 | 2019-06-12 19:53:04.162 | debug | NEW device: 158d0001e827f6(smoke)
mihome.0 | 2019-06-12 19:53:04.161 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d00022a8b06","short_id":28934,"data":{"voltage":3015}}
mihome.0 | 2019-06-12 19:53:04.161 | debug | data: 158d00022a8b06(motion): {"voltage":3.015,"percent":66.1}
mihome.0 | 2019-06-12 19:53:04.161 | debug | NEW device: 158d00022a8b06(motion)
mihome.0 | 2019-06-12 19:53:04.161 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d00022c9252","short_id":32524,"data":{"voltage":3022}}
mihome.0 | 2019-06-12 19:53:04.161 | debug | data: 158d00022c9252(switch): {"voltage":3.022,"percent":67.3}
mihome.0 | 2019-06-12 19:53:04.161 | debug | NEW device: 158d00022c9252(switch)
mihome.0 | 2019-06-12 19:53:04.160 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00012a1876","short_id":22146,"data":{"voltage":3025,"status":"open"}}
mihome.0 | 2019-06-12 19:53:04.160 | debug | data: 158d00012a1876(magnet): {"voltage":3.025,"percent":67.9,"state":true}
mihome.0 | 2019-06-12 19:53:04.160 | debug | NEW device: 158d00012a1876(magnet)
mihome.0 | 2019-06-12 19:53:04.160 | debug | RAW: {"cmd":"read_ack","model":"plug","sid":"158d0001bbf974","short_id":36205,"data":{"voltage":3600,"status":"off","inuse":"0","power_consumed":"62255","load_power":"0.00"}}
mihome.0 | 2019-06-12 19:53:04.159 | debug | data: 158d0001bbf974(plug): {"state":false}
mihome.0 | 2019-06-12 19:53:04.159 | debug | NEW device: 158d0001bbf974(plug)
mihome.0 | 2019-06-12 19:53:04.159 | debug | RAW: {"cmd":"read_ack","model":"gateway","sid":"7811dce1644d","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2019-06-12 19:53:04.158 | debug | data: 7811dce1644d(gateway): {"illumination":1292,"connected":true,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2019-06-12 19:53:04.074 | debug | RAW: {"cmd":"get_id_list_ack","sid":"7811dce1644d","token":"Kz3IqqGahwA9ZATr","data":["158d0001bbf974","158d00012a1876","158d00022c9252","158d00022a8b06","158d0001e827f6","158d000269e235","158d00026bb
mihome.0 | 2019-06-12 19:53:04.061 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1644d","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.27"}
mihome.0 | 2019-06-12 19:53:04.061 | info | Change connection status: true
mihome.0 | 2019-06-12 19:53:04.060 | debug | NEW device: 7811dce1644d(gateway)
mihome.0 | 2019-06-12 19:53:03.965 | info | Change connection status: false
mihome.0 | 2019-06-12 19:53:03.867 | info | starting. Version 1.2.6 in /home/pi/node_modules/iobroker.mihome, node: v8.16.0
host.raspberrypi | 2019-06-12 19:53:02.635 | info | instance system.adapter.mihome.0 started with pid 13601
host.raspberrypi | 2019-06-12 19:52:32.614 | info | Restart adapter system.adapter.mihome.0 because enabled
