### ISSUE TITLE
lumi.sensor_motion.aq2 value update interval

### ISSUE THREAD

**Issue by ltsalvatore** [ioBroker/ioBroker.mihome#67]
Hi, 

i have a question regarding the lumi.sensor_motion.aq2.

i've noticed that the lumi.sensor_motion.aq2 in combination with the mihome.0 adapter provides information with bigger gaps than i.e. the zigbee.0 adapter does. 

for example:
the zigbee.0 updates the state value of **no_motion** in 10 seconds steps whereas the 
mihome.0 adapters starts with 120seconds and updates the value only every 60 seconds.

is there any chance to adapt the update interval so that it matches the same as the zigbee.0 adapter?

**Comment by m0rph2k** [comment]
Yes pls !!!

**Comment by GermanBluefox** [comment]
No idea...

**Comment by Ilovegym66** [comment]
it's not possible to change this in the adapter, because the sensors send the information from itself, if something changed. So we must change the firmware in the sensor, to change the update interval.
And sorry, I see no chance to change the firmware in the sensor. 
Here is a good javascript for the Sensors:
https://github.com/Mic-M/iobroker.xiaomi-aquara-motion-control

**Comment by ltsalvatore** [comment]
> it's not possible to change this in the adapter, because the sensors send the information from itself, if something changed. So we must change the firmware in the sensor, to change the update interval.
> And sorry, I see no chance to change the firmware in the sensor.
> Here is a good javascript for the Sensors:
> https://github.com/Mic-M/iobroker.xiaomi-aquara-motion-control

sorry. .but i dont get it.. 
the sensor sends the information from itself at least every 10 seconds, considering that the zigbee.0 adapter is being updated ever ten seconds. 

so why is the firmware the problem if the mihome.0 adapter reacts slower even though the firmware sends in at least in 10 seconds steps.

**Comment by Ilovegym66** [comment]
two things:
1)
it can be, that the zigbee Adapter actualize every 10sec, but I'm shure, that the motion device don't send every 10 sec new informations, if it's really so, they must have a special long-time-battery insert... :-) - my sensors are more as one year old, with the first battery... 

2)
this issue is for the MiHome-Adapter, so we can only investigate, what the Gateway send... or you must change the software in the gateway...

In the App I've a delay of 1minute, no more entrys in a shorter time.
@ltsalvatore can you provide us a zigbee protocoll with debug level, that we can see, what the sensor send out..??

**Comment by ltsalvatore** [comment]
@Ilovegym66 
sure.. i can send the log.. 
currently i am planning to move my iobroker from Raspberry to NUC and after that i will reconnect the zigbee stick again. 

will update soon
